### ISSUE TITLE
UI to look up status of phone number

### ISSUE THREAD

**Issue by ErrorsAndGlitches** [ColectivaLegal/ScalaSmsAlertSystem#28] opened 2018-01-04 01:13 UTC
We've gotten issues where something is or is not working for a person. Folks part of the tech team should be able to log in and see what the status of a given phone number is.

**Comment by joshmcfarlane** [comment] 2018-01-05 06:33
Resolving this as a duplicate of https://github.com/ColectivaLegal/ScalaSmsAlertSystem/issues/6

**Closed by joshmcfarlane** 2018-01-05 06:33 UTC
